### ISSUE TITLE
Explain memory_order for atomic_intrusive_queue

### ISSUE THREAD

**Issue by MBkkt** [facebookexperimental/libunifex#267]
Hi there are memory_orders chosen for this data structure, but it is not very clear how some of them were chosen.
###### There is no release here, why?
https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L122
https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L138
https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L175
###### There is acquire here, why? We doesn't use old value after success. But I don't fully understand, I would assume that release is needed here.
https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L67
```
... compare_exchange_strong(...., std::memory_order_release,
                                  std::memory_order_relaxed)
```
###### In this case, it seems that you can replace with release and acquire?
https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L92
https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L108
```
... oldValue = head.load(std::memory_order_acquire);
do {
...
} while(!head.compare_exchange_weak(oldValue, item, 
                                    std::memory_order_release,
                                    std::memory_order_acquire));
```

**Comment by lewissbaker** [comment]
> There is no release here, why?

This is because these operations are writing `nullptr` to the atomic value (indicating an empty list).
Any other thread that subsequently reads the `nullptr` value is not going to try to subsequently read any data that was written prior to the `nullptr` being written (ie. there doesn't need to be a synchronises-with relationship here).

> There is acquire here, why? We doesn't use old value after success.

The intention behind the use of `try_mark_active()` and `try_mark_inactive()` is that a consumer thread will usually publish some event handle somewhere that indicates how it can be woken up and then will call `try_mark_inactive()` or `try_mark_inactive_or_dequeue_all()` to mark that the consumer thread has gone to sleep. This operation should have `release` semantics so that it synchronises with a subsequent producer thread that tries to enqueue an item to the queue and finds that the consumer was inactive and thus that it needs to be woken up. The enqueue has acq-rel semantics (rel for the store of the queue item and acquire so that a prior `try_mark_inactive()` synchronises with it. This synchronises-with relationship allows the producer thread to then have visibility of the write that stored the event-handle needed to wake up the consumer.

The `try_mark_active()` method also has `acquire` semantics so that it is consistent with other methods that transition from inactive->active, although its use is somewhat different from the `enqueue()` methods.

The `try_mark_active()` method is also used by `async_mutex::try_lock()` which needs to have acquire semantics.

> In this case, it seems that you can replace with release and acquire?
> https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L92

If we split out the compare_exchange_weak shared between the two branches into two separate compare_exchange_weak operations then each of those could in theory have different weaker memory orders.

e.g.
```
    while (true) {
      if (oldValue == inactive) {
        if (head_.compare_exchange_weak(oldValue, nullptr, std::memory_order_acquire)) {
          return false;
        }
      } else {
        item->*Next = static_cast<Item *>(oldValue);
        if (head_.compare_exchange_weak(oldValue, item, std::memory_order_release, std::memory_order_acquire)) {
          return true;
        }
      }
    }
```

It is currently using acq_rel because it is using a single compare_exchange_weak() call and thus needs to be at least as strong as both cases.

> https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/detail/atomic_intrusive_queue.hpp#L108

Similarly for here, I think, although the use of the ternary operator makes the separate control flow less obvious.

**Comment by MBkkt** [comment]
>The intention behind the use of try_mark_active() and try_mark_inactive() is that a consumer thread will usually publish some event handle somewhere that indicates how it can be woken up and then will call try_mark_inactive() or try_mark_inactive_or_dequeue_all() to mark that the consumer thread has gone to sleep. This operation should have release semantics so that it synchronises with a subsequent producer thread that tries to enqueue an item to the queue and finds that the consumer was inactive and thus that it needs to be woken up. The enqueue has acq-rel semantics (rel for the store of the queue item and acquire so that a prior try_mark_inactive() synchronises with it. This synchronises-with relationship allows the producer thread to then have visibility of the write that stored the event-handle needed to wake up the consumer.

Thanks for the detailed answer. I think I understood it
