### ISSUE TITLE
how to cancel task in static_thread_pool queue?

### ISSUE THREAD

**Issue by Meigumikato** [facebookexperimental/libunifex#456]
how to cancel task in static_thread_pool queue

**Comment by janondrusek** [comment]
I'll need a concrete example of you are trying to achieve in other to be able help. Preferably a [godbolt.org](https://godbolt.org/) link.

**Comment by lewissbaker** [comment]
The static_thread_pool class does not eagerly remove a task from the thread pool work queue when stop is requested, it still waits until the task gets to the front of the queue and then calls set_done() instead of set_value() if stop had beed requested by that time.

We would need to do some more work to handle completing the item sooner when stop is requested if that is what you want.

Otherwise you can just use any of the stop-requesting algorithms to cancel the schedule op (like stop_when()).

**Comment by Meigumikato** [comment]
thanks for your answer
